version: '2'
services:
  gui:
    restart: "no"
    container_name: gui
    build:
      context: .
      dockerfile: ./dockerfiles/GUI/Dockerfile
    ports:
      - 3000:8080
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"